on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

name: Run Tox tests

jobs:
  tox_test:
    name: Tox test
    steps:
    - uses: actions/checkout@v2
    - name: Run Tox tests
      id: test
      uses: fedora-python/tox-github-action@main
      with:
        tox_env: ${{ matrix.tox_env }}
    strategy:
      matrix:
        tox_env: [py38, py39, py310, py311, py312, lint]

    # Use GitHub's Linux Docker host
    runs-on: ubuntu-latest
